import{a as u,i}from"./assets/vendor-Cl-WcV8j.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const s={body:document.querySelector("body"),weatherList:document.querySelector("#weather-list"),themeToggle:document.querySelector("#themeToggle"),form:document.querySelector("#weather-form"),loaderSpan:document.querySelector(".loader")},l="theme";function d(){return JSON.parse(localStorage.getItem(l))}function m(t){localStorage.setItem(l,JSON.stringify(t))}function f(){const t=d();s.body.classList=t}function h(){s.body.classList.toggle("theme-dark"),s.body.classList.toggle("theme-light");const t=s.body.classList.value;m(t)}async function p(t="",o=1){return(await u.get("http://api.weatherapi.com/v1/forecast.json",{params:{key:"56039d7908c048a0890183312252307",q:t,days:o,lang:"uk"}})).data}function y(){s.loaderSpan.classList.remove("hidden")}function g(){s.loaderSpan.classList.add("hidden")}function L(t){const o=t.map(({date:a,day:{avgtemp_c:n,condition:{icon:e,text:r}}})=>`
        <li class="weather-card">
            <img src="${e}" alt="${r}" class="weather-icon"/>
            <h2 class="weather-date">${a}</h2>
            <h3 class="weather-text">${r}</h3>
            <h3 class="temperature">${n} °C</h3>
        </li>
        `).join("");s.weatherList.insertAdjacentHTML("beforeend",o)}function S(){s.weatherList.innerHTML=""}function w(t){const o=t==="";return o&&i.warning({title:"Порожньо",message:"Введіть місто",position:"bottomCenter"}),o}async function T(t){t.preventDefault(),S();const{city:o,days:a}=t.currentTarget.elements;if(!w(o.value.trim())){y();try{const n=await p(o.value.trim(),a.value);L(n.forecast.forecastday)}catch(n){i.error({title:n.message})}finally{g()}}}f();s.themeToggle.addEventListener("click",h);s.form.addEventListener("submit",T);
//# sourceMappingURL=index.js.map
